/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package student_management_system;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author kashan
 */
public class ClassForm extends javax.swing.JPanel {

    static void forName(String commysqljdbcDriver) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
JFrame J;
ConnectDB db = new ConnectDB();

    /**
     * Creates new form Class
     */
    public ClassForm(JFrame t) {
        initComponents();
        setSize(564,392);
        setLocation(400,100);
        
        J=t;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255,80));
        jPanel1.setForeground(new java.awt.Color(102, 255, 102));
        jPanel1.setAlignmentY(2);
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Class_Name");
        jLabel2.setAlignmentY(2);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 145, 99, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("std_id");
        jLabel3.setAlignmentY(2);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(80, 180, 100, 36);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Subject_id");
        jLabel4.setAlignmentY(2);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(80, 220, 86, 40);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Teacher_id");
        jLabel5.setAlignmentY(2);
        jPanel1.add(jLabel5);
        jLabel5.setBounds(80, 265, 100, 30);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Room_id");
        jLabel6.setAlignmentY(2);
        jPanel1.add(jLabel6);
        jLabel6.setBounds(80, 305, 73, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Start_date");
        jLabel7.setAlignmentY(2);
        jPanel1.add(jLabel7);
        jLabel7.setBounds(80, 345, 86, 30);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("End_date");
        jLabel8.setAlignmentY(2);
        jPanel1.add(jLabel8);
        jLabel8.setBounds(80, 380, 77, 40);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Start_time");
        jLabel9.setAlignmentY(2);
        jPanel1.add(jLabel9);
        jLabel9.setBounds(80, 425, 86, 30);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("End_time");
        jLabel10.setAlignmentY(1);
        jPanel1.add(jLabel10);
        jLabel10.setBounds(80, 465, 77, 30);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Class_id");
        jLabel11.setAlignmentY(2);
        jPanel1.add(jLabel11);
        jLabel11.setBounds(80, 100, 79, 30);
        jPanel1.add(jTextField10);
        jTextField10.setBounds(210, 260, 190, 34);

        jPanel3.setBackground(new java.awt.Color(255, 153, 153,80));
        jPanel3.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel13.setText("  Class Info");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(95, 13, 277, 48);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(29, 24, 0, 0);
        jPanel1.add(jTextField11);
        jTextField11.setBounds(210, 300, 190, 34);
        jPanel1.add(jTextField12);
        jTextField12.setBounds(210, 220, 190, 34);
        jPanel1.add(jTextField13);
        jTextField13.setBounds(210, 140, 190, 34);
        jPanel1.add(jTextField15);
        jTextField15.setBounds(210, 180, 190, 34);
        jPanel1.add(jTextField16);
        jTextField16.setBounds(210, 340, 190, 34);
        jPanel1.add(jTextField17);
        jTextField17.setBounds(210, 380, 190, 34);
        jPanel1.add(jTextField18);
        jTextField18.setBounds(210, 460, 190, 34);
        jPanel1.add(jTextField19);
        jTextField19.setBounds(210, 420, 190, 34);
        jPanel1.add(jTextField20);
        jTextField20.setBounds(210, 100, 190, 34);

        jPanel2.setBackground(new java.awt.Color(255, 51, 51,80));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel14.setText("Class Info");
        jPanel2.add(jLabel14);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(30, 10, 390, 70);

        add(jPanel1);
        jPanel1.setBounds(240, 70, 440, 520);

        jButton2.setBackground(new java.awt.Color(255, 204, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(550, 600, 120, 50);

        jButton3.setBackground(new java.awt.Color(255, 204, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setText("Submit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(680, 600, 120, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student_management_system/images (3) (1) (1) (2).jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(0, 0, 870, 680);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      String title="Back";
        
        if(title.equals("Back")){
            J.dispose();
            JFrame frame = new JFrame();
            frame.setSize(941,558);
            frame.setLocationRelativeTo(null);
            frame.setUndecorated(true);
            HomeScreen s = new HomeScreen(frame);
            frame.add(s);
            this.setVisible(false);
                    
            frame.setVisible(true);      
    }                             
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
//        try {
//       
//        int sid = Integer.parseInt(name1.getText());
//        String sname1 = name1.getText();
//        String sname2 = name2.getText();
//        String sphone = phone.getText();
//        String saddress = address.getText();
//        String sdate = date.getText();
//        String sage = age.getText();
//            Statement statement = conn.createStatement();
//            String sql = "INSERT into student (student_id, first_name) VALUES (3, \'asfand\')";
//            ResultSet rs = statement.executeQuery(sql);
//            
//            conn.close();
//    } catch (SQLException ex) {
//        Logger.getLogger(addStudent.class.getName()).log(Level.SEVERE, null, ex);
//    }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    // End of variables declaration//GEN-END:variables

    private void dispose() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
