/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package student_management_system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author kashan
 */
public class Rooms extends javax.swing.JPanel {
JFrame J;
ConnectDB db = new ConnectDB();
    /**
     * Creates new form Rooms
     */
    public Rooms(JFrame t) {
        initComponents();
         setSize(826,468);
        setLocation(400,100);
        J=t;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        no = new javax.swing.JTextField();
        type = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 255, 102,70));
        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 0, 0,130));
        jPanel3.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(153, 255, 153,80));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("            Room Info");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(37, 13, 392, 75);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 0, 0, 0);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Room_id");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 160, 130, 22);

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        jPanel1.add(id);
        id.setBounds(220, 160, 190, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Room_no");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 220, 130, 25);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Room_type");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 280, 120, 25);
        jPanel1.add(no);
        no.setBounds(220, 220, 190, 30);
        jPanel1.add(type);
        type.setBounds(220, 280, 190, 30);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(240, 350, 100, 40);

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(360, 350, 100, 40);

        jPanel2.setBackground(new java.awt.Color(204, 0, 0,70));
        jPanel2.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setText("        Room_Info");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(40, 30, 300, 40);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(30, 20, 410, 80);

        add(jPanel1);
        jPanel1.setBounds(130, 40, 470, 400);

        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student_management_system/download (6) (1).jpg"))); // NOI18N
        add(jLabel51);
        jLabel51.setBounds(0, 0, 830, 470);

        jLabel7.setText("jLabel7");
        add(jLabel7);
        jLabel7.setBounds(0, 0, 160, 210);
        add(jLabel9);
        jLabel9.setBounds(0, 0, 780, 470);
    }// </editor-fold>//GEN-END:initComponents

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         String title="subject_registration";
        
        if(title.equals("subject_registration")){
            J.dispose();
            JFrame frame = new JFrame();
            frame.setSize(941,558);
            frame.setLocationRelativeTo(null);
            frame.setUndecorated(true);
            HomeScreen s = new HomeScreen(frame);
            frame.add(s);
            this.setVisible(false);
                    
            frame.setVisible(true);      
    }                             
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
       
        int rid = Integer.parseInt(id.getText());
        int rno = Integer.parseInt(no.getText());
        String rtype = type.getText();
        
        
        Class.forName("com.mysql.cj.jdbc.Driver");  
        Connection con = DriverManager.getConnection(  
        "jdbc:mysql://localhost:3306/student_management_system","root","root");  
       Statement stmt = con.createStatement();
       String query = "insert into rooms values ('"+rid+"', '"+rno+"', '"+rtype+"')";
       int b = stmt.executeUpdate(query);
       // if b == 1 then execute successfully.
   //for quering       
   //stmt.executeQuery(query);
        
       
            /*
            String sql = new StringBuilder().
                    append("INSERT INTO parent(parent_id, parent_name, parent_phone_no, parent_occupation) VALUES (").
                    append(id).
                    append(", \'").append(name).append("\', \'").append(phone).
                    append("\', \'").append(occup).toString();
//
            */
            
            
    } catch (Exception ex) {
        Logger.getLogger(addStudent.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField no;
    private javax.swing.JTextField type;
    // End of variables declaration//GEN-END:variables

    private void dispose() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
