/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package student_management_system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author kashan
 */
public class Teachers extends javax.swing.JPanel {
JFrame j;
ConnectDB db = new ConnectDB();
    /**
     * Creates new form Teachers
     */
    public Teachers(JFrame t) {
        initComponents();
         setSize(975,539);
        setLocation(400,100);
        j=t;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        mail = new javax.swing.JTextField();
        gender = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jdate = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        phone = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 255, 255,80));
        jPanel2.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(255, 0, 0,80));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("  Teacher_Informaton");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jLabel2)
                .addContainerGap(131, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(22, 22, 22))
        );

        jPanel2.add(jPanel4);
        jPanel4.setBounds(10, 10, 620, 70);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Phone");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(140, 226, 140, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("email");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(140, 180, 160, 40);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setText("Gender");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(140, 270, 130, 30);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("Teacher_id");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(140, 106, 170, 30);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setText("Name");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(140, 150, 160, 30);
        jPanel2.add(id);
        id.setBounds(330, 110, 160, 30);

        mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mailActionPerformed(evt);
            }
        });
        jPanel2.add(mail);
        mail.setBounds(330, 190, 160, 30);
        jPanel2.add(gender);
        gender.setBounds(330, 270, 160, 30);
        jPanel2.add(name);
        name.setBounds(330, 150, 160, 30);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setText("Join_date");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(140, 310, 120, 30);
        jPanel2.add(jdate);
        jdate.setBounds(330, 310, 160, 30);

        jButton1.setBackground(new java.awt.Color(204, 153, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(470, 420, 120, 40);

        jButton3.setBackground(new java.awt.Color(204, 153, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(330, 420, 120, 40);
        jPanel2.add(phone);
        phone.setBounds(330, 230, 160, 30);

        add(jPanel2);
        jPanel2.setBounds(190, 40, 640, 470);
        add(jLabel9);
        jLabel9.setBounds(0, 0, 980, 540);
    }// </editor-fold>//GEN-END:initComponents

    private void mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mailActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String title="Back";
        
        if(title.equals("Back")){
            j.dispose();
            JFrame frame = new JFrame();
            frame.setSize(941,558);
            frame.setLocationRelativeTo(null);
            frame.setUndecorated(true);
            HomeScreen s = new HomeScreen(frame);
            frame.add(s);
            this.setVisible(false);
                    
            frame.setVisible(true);      
    }                             
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
       
        int tid = Integer.parseInt(id.getText());
        String tname = name.getText();
        String tphone = phone.getText();
        String tmail = mail.getText();
        String tgender = gender.getText();
        int tjoindate = Integer.parseInt(jdate.getText());
        
        Class.forName("com.mysql.cj.jdbc.Driver");  
        Connection con = DriverManager.getConnection(  
        "jdbc:mysql://localhost:3306/student_management_system","root","root");  
       Statement stmt = con.createStatement();
       String query = "insert into teacher values ('"+tid+"', '"+tname+"', '"+tphone+"', '"+tmail+"', '"+tgender+"', '"+tjoindate+"')";
       int b = stmt.executeUpdate(query);
       // if b == 1 then execute successfully.
   //for quering       
   //stmt.executeQuery(query);
        
       
            /*
            String sql = new StringBuilder().
                    append("INSERT INTO parent(parent_id, parent_name, parent_phone_no, parent_occupation) VALUES (").
                    append(id).
                    append(", \'").append(name).append("\', \'").append(phone).
                    append("\', \'").append(occup).toString();
//
            */
            
            
    } catch (Exception ex) {
        Logger.getLogger(addStudent.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField gender;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jdate;
    private javax.swing.JTextField mail;
    private javax.swing.JTextField name;
    private javax.swing.JTextField phone;
    // End of variables declaration//GEN-END:variables

    private void dispose() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
